site_name: Tech's Plugin Documentation

repo_name: '/techscode/TechsCodeDoc'
repo_url: 'https://github.com/techscode/techscodedoc'

copyright: 'Copyright &copy; 2018 TechsCode'

theme:
  name: null
  custom_dir: 'theme'
  language: 'en'

  palette:
    primary: 'indigo'
    accent: 'indigo'

  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'

  logo: 'images/logo.png'

  feature:
    tabs: true

markdown_extensions:
  - admonition

extra:
  social:
    - type: 'github'
      link: 'https://github.com/techscode'
    - type: 'twitter'
      link: 'https://twitter.com/techscode'
    - type: 'instagram'
      link: 'https://instagram.com/techscodes'
